fragment simplifiedTrain on Train {
  trainNumber
  commuterLineid
  departureDate
  trainType {
    name
  }
  cancelled
  version
  timeTableRows {
    scheduledTime
    liveEstimateTime
    type
    commercialTrack
    station {
      name
      shortCode
    }
  }
}
