packages:
  - packages/*
  - tooling/*
  - site

catalog:
  eslint: ^9.33.0
  typescript: ^5.9.2
  vitest: ^3.2.4

catalogs:
  react19:
    '@types/react': ^19.1.9
    '@types/react-dom': ^19.1.7
    react: ^19.1.1
    react-dom: ^19.1.1
