schema: 'https://rata.digitraffic.fi/api/v2/graphql/graphql'
overwrite: true
documents:
  - '**/*.gql'
generates:
  ./generated/graphql.tsx:
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-react-query'
    config:
      fetcher:
        endpoint: https://rata.digitraffic.fi/api/v2/graphql/graphql
        fetchParams:
