/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutSettingsImport } from './routes/_layout/settings'
import { Route as LayoutStationImport } from './routes/_layout/$station'
import { Route as LayoutTrainDepartureDateTrainNumberImport } from './routes/_layout/train.$departureDate.$trainNumber'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSettingsRoute = LayoutSettingsImport.update({
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutStationRoute = LayoutStationImport.update({
  path: '/$station',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutTrainDepartureDateTrainNumberRoute =
  LayoutTrainDepartureDateTrainNumberImport.update({
    path: '/train/$departureDate/$trainNumber',
    getParentRoute: () => LayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/$station': {
      id: '/_layout/$station'
      path: '/$station'
      fullPath: '/$station'
      preLoaderRoute: typeof LayoutStationImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/train/$departureDate/$trainNumber': {
      id: '/_layout/train/$departureDate/$trainNumber'
      path: '/train/$departureDate/$trainNumber'
      fullPath: '/train/$departureDate/$trainNumber'
      preLoaderRoute: typeof LayoutTrainDepartureDateTrainNumberImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  LayoutRoute: LayoutRoute.addChildren({
    LayoutStationRoute,
    LayoutSettingsRoute,
    LayoutIndexRoute,
    LayoutTrainDepartureDateTrainNumberRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/$station",
        "/_layout/settings",
        "/_layout/",
        "/_layout/train/$departureDate/$trainNumber"
      ]
    },
    "/_layout/$station": {
      "filePath": "_layout/$station.tsx",
      "parent": "/_layout"
    },
    "/_layout/settings": {
      "filePath": "_layout/settings.tsx",
      "parent": "/_layout"
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/train/$departureDate/$trainNumber": {
      "filePath": "_layout/train.$departureDate.$trainNumber.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
