# On push to main run tests and then push changes to server.

name: Test and deploy

on:
  push:
    paths-ignore:
      - '**README.md'
      - 'docs/**'
    branches: [main]

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml
    secrets:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

  deploy:
    runs-on: ubuntu-latest
    needs: test
    name: Deploy to production

    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Restart Node Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/junat.live
            git fetch origin main
            git reset --hard FETCH_HEAD
            git clean -d -f
            yarn --frozen-lockfile
            chown $(whoami) . # PM2 doesn't recognize root user from Github Actions
            yarn build --filter=site && rsync -va $(pwd)/site/tmp/ $(pwd)/site/.next && rm -rf $(pwd)/site/tmp/
            pm2 start -s

  purge-cache:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Purge Cloudflare cache
        uses: jakejarvis/cloudflare-purge-action@v0.3.0
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
